# Generated by Django 3.2.7 on 2021-10-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_otp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
